# Generated by Django 4.2.5 on 2023-09-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
